### ISSUE TITLE
Scope Claims Data Quality Profiling MVP

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/claims_preprocessing_snowflake#44]
Both Icon and Firsthand are asking for claims data profiling and we believe many organizations with claims data will benefit from this.

- [ ] Figure out the the scope of this (i.e. the specific problems we should aim to solve and ideas for how we solve them).

**Comment by sarah-tuva** [comment]
[Miro board](https://miro.com/app/board/uXjVOj__uk8=/) created that scopes this project. I'll add some issues into the backlog when I get the new repo created.
